config/routes.rb
Rails.application.routes.draw do

	root to: "welcome#home"

  		# get '/' => 'welcome#home'

  	devise_for :users
  		resources :contacts, only:[:new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "javimaci76@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  	@contact = Contact.new

  end

  def create

  		@contact = Contact.new(params[:contact])
  		@contact.request = request
  		if @contact.deliver
  			flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
  		else
  			flash.now[:error] = 'Cannot send message.'
  			render :new
  		end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def home
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
  <h3> Thank you for your message. </h3>

 
  <p> We'll get back to you as soon as possible. </p>

  
  <p> <%= link_to 'Home', root_url, :class => 'button' %></p>

app/views/contacts/new.html.erb
<div class="container">
    <div class="row">
        <div class="col m10 offset-m1 s12">
            <h2 class="center-align">Contact Us</h2>
            <div class="row">
                <%= simple_form_for @contact, :html => {:class => 'col s12' } do |f| %>
                <div class="row">
                    <div class="input-field col m6 s12">
                        <%= f.input :name, :required => true, :class => "validate", :id => "first_name" %>
                    </div>
                    <div class="input-field col m6 s12">
                        <%= f.input :email, :required => true %>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col m12 s12">
                        <%= f.input :message, :as => :text, :required => true %>
                    </div>
                    <div class= "hidden">
                        <%= f.input :nickname, :hint => 'Leave this field blank!' %>
                    </div>
                </div>
                <div>

                    <div class="row">
                        <div class="col m6">
                             </br>
                                <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EMEA</title>
    <%= csrf_meta_tags %>
  		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>

    <%= yield %>
  </body>
</html>

app/views/welcome/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <title>EMEA</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>
<body>
  <nav class="white" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" class="brand-logo" ><img class= "main-logo" src="<%=image_url("logo.jpg") %>"></a>
      <ul class="right hide-on-med-and-down ">
        <li><a class="logo light-blue-text text-darken-4" href="#about_emea">About US</a></li>
        <li><a class="logo light-blue-text text-darken-4" href="#products_of_emea">Products</a></li>
        <li><a class="logo light-blue-text text-darken-4" href="#contact_emea">Contact</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav" >
        <li><a class="logo light-blue-text text-darken-4" href="#about_emea">About US</a></li>
        <li><a class="logo light-blue-text text-darken-4" href="#products_of_emea">Products</a></li>
        <li><a class="logo light-blue-text text-darken-4" href="#contact_emea">Contact</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center light-blue-text text-darken-4">EMEA</h1>
        <div class="row center">
          <h5 class="header col s12 light-blue-text text-darken-4">Consulting Services</h5>
        </div>
<!--         <div class="row center">
          <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Started</a>
        </div> -->
        <br><br>

      </div>
    </div>
    <div class="parallax"><img src="<%=image_url("city.jpg")%>" alt="Unsplashed background img 1"></div>
  </div>


  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <a id="about_emea"></a>
            <h2 class="center blue-text"><i class="material-icons">business</i></h2>
            <h5 class="center">Experience</h5>
            <p class="light main">EMEA’s management team has over 15 years of experience consulting, for telecom and technology companies. Our wide-ranging experience allows us to provide outstanding consulting services to our clients, who we proudly refer to as partners.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center blue-text"><i class="material-icons">group</i></h2>
            <h5 class="center">Innovation</h5>

            <p class="light main">EMEA Consulting Services helps its partners to transform their organizations through the adoption of innovative technological solutions. Firstly, we identify our partner’s needs and areas to optimize. Secondly, we define and develop digital solutions to solve these issues. Finally, we work, hand in hand, on the tactics, strategy, and implementation needed to optimize our partner's businesses, driving innovation, flexibility, and profitability.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center blue-text"><i class="material-icons">speaker_notes</i></h2>
            <h5 class="center">Flexibility</h5>

            <p class="light main">EMEA Consulting Services understand that small, medium and large enterprises need services for specific projects either on a short or long-term basis, and we always tailor our services accordingly.</p>
          </div>
        </div>
      </div>

    </div>
  </div>
  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light">Network Products</h5>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="<%=image_url("iot.jpg") %>" alt="Unsplashed background img 2"></div>
  </div>

  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s6">
          <div class="icon-block">
          <a id="products_of_emea"></a>
            <h2 class="center blue-text"><i class="material-icons">speaker_phone</i></h2>
            <h5 class="center">GSM</h5>

            <p class="light main">EMEA Consulting Services design, develop and deploy GSM networks on behalf of long distance telecom carriers. Our partners are ranked in the top 10 list of international telecom wholesale carriers. We successfully deployed networks in the top largest economies in Latin America, Mexico, and Brazil. These networks provide superior voice quality and deliver significant cost savings.</p>
          </div>
        </div>

        <div class="col s6">
          <div class="icon-block">
            <h2 class="center blue-text"><i class="material-icons">language</i></h2>
            <h5 class="center">IoT</h5>

            <p class="light main">EMEA Consulting Services also specializes in the design, development, and deployment of Low-Power, Wide-Area (LPWA). LPWA unlocks new market potential by lowering costs and increasing the flexibility of solution deployment.</p>
          </div>
        </div>

      </div>

    </div>
  </div>



  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light">Customized Cloud Solutions</h5>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="<%=image_url("cyber.jpg") %>" alt="Unsplashed background img 2"></div>
  </div>

  <div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12 center">
         <div class="icon-block">
          <h2 class="center blue-text"><i class="material-icons">cloud</i></h2>

          <h4>Cloud Solutions</h4>
          <p class="left-align light main">EMEA Consulting Services is a strong advocate of the benefits offered by Cloud technology. Our consultants constantly help our partners to choose the best Cloud solution for their needs. We specialize in Digital telephony and collaboration services, Cybersecurity, OTT video platform and Cloud computing.</p>
        </div>
       </div>
      </div>

    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light">Securing your data is our priority</h5>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="<%=image_url("eye.jpg") %>" alt="Unsplashed background img 3"></div>
  </div>

  <footer class="page-footer blue darken-4">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
         <a id="contact_emea"></a>
          <h5 class="white-text">Contact us</h5>
          <p class="grey-text text-lighten-4"></p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">By phone</h5>
          <ul>
            <li><a class="white-text" href="#!"> +1-305-860-9191</a></li>
<!--             <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li> -->
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">By email</h5>

          <ul>
            <li><a class="white-text"><%= link_to 'sales@emeaconsultingservices.com', new_contact_path, :class => 'white-text button' %></a></li>
<!--             <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li> -->
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="white-text container">
      Address : <a class="white-text" href="http://materializecss.com">1115 Camellia Weston, FL 33326. USA</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>


  </body>
</html>